### ISSUE TITLE
Plugin can't find `annotations` on dashboard

### ISSUE THREAD

**Issue by stuartnelson3** [mtanda/grafana-histogram-panel#36]
I'm getting a JS error when attempting to use this plugin:

```
Cannot read property 'annotations' of undefined
```

trace:

```
TypeError: Cannot read property 'annotations' of undefined
    at a.getGlobalAnnotations (http://grafana.int.s-cloud.net/public/app/boot.3eefa81c.js:10:23764)
    at a.getAnnotations (http://grafana.int.s-cloud.net/public/app/boot.3eefa81c.js:10:22682)
    at HistogramCtrl.issueQueries (http://grafana.int.s-cloud.net/public/plugins/mtanda-histogram-panel/histogram_ctrl.js?bust=1476088772806:240:59)
    at g (http://grafana.int.s-cloud.net/public/app/boot.3eefa81c.js:38:2224)
    at http://grafana.int.s-cloud.net/public/app/boot.3eefa81c.js:38:2396
```

Looking in my console it seems to be blowing up at:

```
d=this,e=a.dashboard;if(0===e.annotations.list.length)return this.$q.when([]);
```

(boot.3eefa81c.js:10)

Looking at the code it seems like the service is being injected fine, so I'm wondering if there's some sort of configuration I need to do? I added an annotation to the dashboard to see if that was the issue but I still get the same error.

Any ideas?

**Comment by mtanda** [comment]
Thanks for reporting :-)

In recent Grafana version, this plugin doesn't work due to annotation service interface change.

I try to fix it. Please test this version.
https://github.com/mtanda/grafana-histogram-panel/pull/37

**Comment by stuartnelson3** [comment]
Works, great! Thanks!
