### ISSUE TITLE
Cannot read property 'annotations' of undefined

### ISSUE THREAD

**Issue by davewongillies** [mtanda/grafana-histogram-panel#54]
When trying to use this with grafana 4.x, we're seeing this error making the panel unusable:

```
Message:
Cannot read property 'annotations' of undefined

Stack trace:
TypeError: Cannot read property 'annotations' of undefined
    at a.getGlobalAnnotations (https://grafana-server/public/app/boot.85c49108.js:10:21230)
    at a.getAnnotations (https://grafana-server/public/app/boot.85c49108.js:10:20148)
    at HistogramCtrl.issueQueries (https://grafana-server/public/plugins/mtanda-histogram-panel/histogram_ctrl.js?bust=1481603289191:240:59)
    at g (https://grafana-server/public/app/boot.85c49108.js:38:29545)
    at https://grafana-server/public/app/boot.85c49108.js:38:29717
    at o.$eval (https://grafana-server/public/app/boot.85c49108.js:39:5357)
    at o.$digest (https://grafana-server/public/app/boot.85c49108.js:39:3843)
    at https://grafana-server/public/app/boot.85c49108.js:39:5444
    at f (https://grafana-server/public/app/boot.85c49108.js:37:15604)
    at https://grafana-server/public/app/boot.85c49108.js:37:17066
```

**Comment by mtanda** [comment]
Sorry for late response.
Please try v0.1.6, it should work with Grafana 4.0.

https://github.com/mtanda/grafana-histogram-panel/pull/37

**Comment by davewongillies** [comment]
@mtanda thanks! it turned out I somehow ended up with the older *and* the new version installed on my grafana server with the old version being the one that was getting loaded. I removed the old version and all is good :+1:
