### ISSUE TITLE
Cannot read property 'annotations' of undefined

### ISSUE THREAD

**Issue by marcelrv** [mtanda/grafana-histogram-panel#59]
Updated my Grafana to the latest version (4.3.2) from v3.1.

updated to the latest histogram `grafana-cli plugins install mtanda-histogram-panel`

The plug-in used to work just fine, but after the update no longer
in the dashboard it does not show, it gives this error:

```
TypeError: Cannot read property 'annotations' of undefined
    at a.getGlobalAnnotations (http://192.168.3.50:3000/public/app/boot.d709d8d5.js:18:14974)
    at a.getAnnotations (http://192.168.3.50:3000/public/app/boot.d709d8d5.js:18:13713)
    at HistogramCtrl.issueQueries (http://192.168.3.50:3000/public/plugins/mtanda-histogram-panel/histogram_ctrl.js?bust=1498834998629:238:59)
    at i (http://192.168.3.50:3000/public/app/boot.d709d8d5.js:51:24759)
    at http://192.168.3.50:3000/public/app/boot.d709d8d5.js:51:25181
    at o.$eval (http://192.168.3.50:3000/public/app/boot.d709d8d5.js:52:293)
    at o.$digest (http://192.168.3.50:3000/public/app/boot.d709d8d5.js:51:30809)
    at b.$apply (http://192.168.3.50:3000/public/app/boot.d709d8d5.js:52:576)
    at HTMLAnchorElement.<anonymous> (http://192.168.3.50:3000/public/app/boot.d709d8d5.js:54:7608)
    at HTMLAnchorElement.dispatch (http://192.168.3.50:3000/public/app/boot.d709d8d5.js:48:14595)
```

**Comment by mtanda** [comment]
I try to replicate this by using panel plugin ver 0.1.6.
But, I can't replicate...

I'm not sure why the panel doesn't work.
It could be the problem caused by upgrading Grafana and incompatibility of dashboard.
Please try to create new dashboard, and add panel.
